### ISSUE TITLE
Linktap Node Server Not working

### ISSUE THREAD

**Issue by cayeldo** [simplextech/udi-poly-linktap#10]
I have a new Polisy server (5.3) and I installed the Linktap node server.  After adding my credentials, it added three nodes, including the gateway and the front sprinklers.  The issue is in the ISY994, there is no other information other than the Node server is online.  I have restarted the Polisy and polygot servers and have uninstalled and reinstalled the node many times but still have the same results.  Can anyone confirm that this still works?

Thanks!

![Screen Shot 2021-03-27 at 8 55 33 AM](https://user-images.githubusercontent.com/81472589/112721503-74e34c00-8eda-11eb-8d66-3374525cd233.png)

![image](https://user-images.githubusercontent.com/81472589/112721534-b4119d00-8eda-11eb-846d-a1063209ce25.png)

**Comment by simplextech** [comment]
The first screenshot is of the controller node which is just a holder node.  Nodes for the TapLink devices should have also been created for Front Sprinklers.  the Polyglot screenshot shows the node was created.  Was it not also added to the ISY Admin Console?

This NodeServer has been working fine.

**Comment by cayeldo** [comment]
Yes.  It seems that turning on the Linktap device seems to be important.  Doh!  sorry to have wasted your time.  I must have fat fingered the switch while connected it and turned it off by accident.  I turned it on, reinstalled/restarted the node and everything is working great.  Thanks for the fast reply!

**Comment by simplextech** [comment]
No worries I've done that myself.

**Comment by cayeldo** [comment]
Sorry to be a pest, but can I open this up again?  Everything seems to be installed correctly... I see the nodes, etc in ISY, however, when I issue the instant on command, it doesn't work (I have the Linktap on my desk now).  If I initiate the command through the Linktap app, it works fine, but through the ISY it does not.  Even when I have activated watering from the app, the status of the ISY doesn't update.  Any ideas?  I've attached my log file.
[LinkTap_3-27-2021_93807_AM.txt](https://github.com/simplextech/udi-poly-linktap/files/6215731/LinkTap_3-27-2021_93807_AM.txt)

**Comment by simplextech** [comment]
I'll look at the log and re-open the issue.

**Comment by simplextech** [comment]
Log is showing an exception which is odd and new.  You mention this is a new Polisy?  Are you fully up to date and updated the Polisy OS which updates Python as well?  This is done via command line as the update through the Polyglot Interface doesn't fully update everything.  

Can you check the UDI forum for the update procedure, update Polisy and try again?  I'll check back later this evening.

**Comment by cayeldo** [comment]
OK. It is a new Polisy server (received it last week).   I checked with UDI forum and I seem to be running the most recent version of everything on the server...  See the status screen shot.

![image](https://user-images.githubusercontent.com/81472589/112729082-c4d50980-8f00-11eb-9383-9aff97f49623.png)

**Comment by simplextech** [comment]
That information is for Polyglot which is the interface and front end UI you interact with.  You will need to login to the polisy using SSH to then update the OS as well.  This OS update will include a Python update.  Once that's done I'm curious if that resolves it.  If not then I'll have to try and trace it down on my system.

**Comment by cayeldo** [comment]
OK.  I just did SSH access and ran the update/upgrade functions...

[admin@polisy ~]$ sudo pkg update
Updating FreeBSD-base repository catalogue...
FreeBSD-base repository is up to date.
Updating udi repository catalogue...
udi repository is up to date.
All repositories are up to date.
[admin@polisy ~]$ sudo pkg upgrade
Updating FreeBSD-base repository catalogue...
FreeBSD-base repository is up to date.
Updating udi repository catalogue...
udi repository is up to date.
All repositories are up to date.
Checking for upgrades (0 candidates): 100%
Processing candidates (0 candidates): 100%
Checking integrity... done (0 conflicting)
Your packages are up to date.

I'll restart and let you know!

**Comment by cayeldo** [comment]
Still acting the same.  I also checked the OS version...

Welcome to Polisy!
[admin@polisy ~]$ uname -srm
FreeBSD 12.2-RELEASE-p5 amd64
[admin@polisy ~]$ 


Seems like it's the latest, isn't it?

**Comment by simplextech** [comment]
sudo pkg update  
then..
sudo pkg upgrade
- select Y if/when prompted
then reboot

**Comment by cayeldo** [comment]
Done! 

Rebooting now.....

[admin@polisy ~]$ sudo pkg update
Password:
Updating FreeBSD-base repository catalogue...
FreeBSD-base repository is up to date.
Updating udi repository catalogue...
udi repository is up to date.
All repositories are up to date.
[admin@polisy ~]$ sudo pkg upgrade
Updating FreeBSD-base repository catalogue...
FreeBSD-base repository is up to date.
Updating udi repository catalogue...
udi repository is up to date.
All repositories are up to date.
Checking for upgrades (0 candidates): 100%
Processing candidates (0 candidates): 100%
Checking integrity... done (0 conflicting)
Your packages are up to date.
[admin@polisy ~]$

**Comment by cayeldo** [comment]
No changes...  Instant on function, does not work.  

![image](https://user-images.githubusercontent.com/81472589/112734305-55204800-8f1b-11eb-8422-f8462b9b7f60.png)

**Comment by cayeldo** [comment]
Just in case it's important, I also checked the version of Python running....

Python 3.7.10
[admin@polisy ~]$

**Comment by simplextech** [comment]
Interesting.  I'll have to see what has happened.

**Comment by macjeff** [comment]
I am having the same issue.  I will PM you with my my information so you can test with my system.  The nodes show up but they have all null info False for online when its online. Battery at zero.   nothing works.

I last used this last October so something happened.  Tried to uninstall and reinstall and no luck.

**Comment by simplextech** [comment]
The previous issue was the power was turned off on the TapLink unit.  Check the power/batteries.

**Comment by macjeff** [comment]
must be different issue.  BRAND new batteries and everything works fine from the LinkTap app.  See message I posted on UDI (PM to you).   I can post here if you want but sent you more info than I would ever post

**Comment by cayeldo** [comment]
I've actually still had this issue from before.  Was a new version pushed out to resolve it (I posted it on Mar 27th)
