### ISSUE TITLE
Fastest Poll allowed

### ISSUE THREAD

**Issue by macjeff** [simplextech/udi-poly-linktap#2]
Your notes say only the long poll gets the data and you say minimum is 60 seconds.   Can you tell me how to set it to get the fastest poll.  Right now I have it at 

5 min   60 seconds and even then if I water for 2 min I see it change to watering time remaining 2 min about a minute later and then its over before it goes down.

How can I get those numbers to update faster or can we not do that?

**Comment by simplextech** [comment]
They rate limit their API calls to 1 a minute.  Nothing I can do about that.

**Comment by macjeff** [comment]
But what is the fastest setting I can do.

1 min and 60 seconds.   I will close this after you give me the best legal ones to put in there.

**Comment by simplextech** [comment]
1 call per minute is the fastest you can do.  Setting the short poll to 60 seconds is the fastest they allow.

**Comment by macjeff** [comment]
so dont touch the long poll at all?

**Comment by simplextech** [comment]
long poll is not used for anything.  I can't remove it from the interface though... Polyglot thing.

**Comment by macjeff** [comment]
ok thanks
