### ISSUE TITLE
Commands Stopped Working

### ISSUE THREAD

**Issue by macjeff** [simplextech/udi-poly-linktap#5]
I had not done command tests since the 0.1.7 version.   

Now running 0.1.9.

Had to use it today and chose Instant On and did not work.  Tried for a couple valves and had the same issue.   There is an error in the log (Attached)

I then restarted the nodeserver and it started working again.

FYI there was an issue (issue #3) where it was not working then under 0.1.4 and I restarted and it fixed it.  But it worked after that though Tuesday.  I just have not used it since then.

[LinkTap_logs_2020-5-28_120034.zip](https://github.com/simplextech/udi-poly-linktap/files/4696883/LinkTap_logs_2020-5-28_120034.zip)

**Comment by macjeff** [comment]
So it worked after restarting linktap yesterday and now 24 hours later I got the same error when trying to turn on a valve via ISY..

2020-05-29 03:44:13,754 Controller polyinterface      ERROR    polyinterface:write: Exception in thread Controller:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/var/polyglot/.local/lib/python3.7/site-packages/polyinterface/polyinterface.py", line 849, in _parseInput
    self.nodes[input[key]['address']].query()
TypeError: query() missing 1 required positional argument: 'command'

I restarted the node server and it worked right away.

**Comment by simplextech** [comment]
This is coming from a query command:
`self.nodes[input[key]['address']].query()`

I'll look into that.  Are you issuing a query for some reason?

**Comment by macjeff** [comment]
Yes I think you got it!!!   I run a query at 3:30 am every day to make sure my ISY/PLM is showing the correct status.  If you look at the log times today and yesterday it is crashing just after that so you are correct its the query. 

So the next day (like today) I send a control command to linked in but it does not work because it had already crashed at 3am.

So that has to be it.  I did not noticed the time before but the log tells the story.

thanks!!!

**Comment by simplextech** [comment]
v0.1.10 was pushed and should be in the Nodeserver store in about 20 minutes give or take.  This should resolve the query issue.  I'll leave this open until you verify it.

**Comment by macjeff** [comment]
I will reply tomorrow and comment close if fixed

thank you

**Comment by macjeff** [comment]
That seemed to fix it
