### ISSUE TITLE
Re-activate previous watering Plan

### ISSUE THREAD

**Issue by macjeff** [simplextech/udi-poly-linktap#7]
Sent this to you via email but doing the right way.....

Linktap said if you do the below then when you INSTANT ON and it finishes the INSTANT ON the previous watering plan like Odd/Even or Interval will reactivate.

**  Please note that it is NORMAL behavior if you issue and INSTANT OFF (which in the API is INSTANT ON- ZERO minites) it WILL NOT resume your watering plan.  An Instant Off cancels all watering plans.  So in order for the below to work you must let your watering plan finish on its one.

Also.... in order to SAVE your watering plan to the server you must from the app run an instant on for at least a full 60 seconds and let it finish on its own.   So go to the app....go to your valve...Set up your watering plan (other than instant on). then go to instant on and set for 2 minutes.  MAKE SURE you click on the option to resume watering plan (tiny checkbox).  Then activate the instant on and let it finish.  That will save your choice to the server.   After that the API below should work fine.  It may work without doing this if you have done these steps before unintentionally but they told me to make sure you do this.

The following are the API commands for next version....

autoBack: Optional. String or Boolean type. "true" for automatically re-activating the previous watering plan after watering in Instant Mode is completed.

If you add autoBack:  true in the Request, "Reactivating" will work.

**Comment by simplextech** [comment]
I can look at adding the autoBack but isn't the purpose of having a automation controller to perform the scheduling and automatic watering?  When you intermix their app and a control system there are always going to be problems.  It's best to pick one method or the other for controlling the schedule.

**Comment by macjeff** [comment]
For me I use their app for the regular controls but only use the ISY to get around their apps limitations with Alexa.  With their app you have to say Valve 1, Valve 2, etc.  With ISY I can integrate with alexa and say the name of the valve.  

But I see your point.

With that said it wont hurt anyone using only the ISY to add this would it?

**Comment by simplextech** [comment]
I've never used LinkTap with Alexa or Google but I would think you could change the spoken name in the app to reflect whatever you wanted.  

I'm thinking it likely won't affect anyone else but I'm also going to see about making it a config option.

**Comment by macjeff** [comment]
The instructions and reviews clearly say at this time you have to address the valve by number as it wont recognize the name added in the app.  If you use a name it defaults to the first valve and someone wrote a review saying thats bad because you think it activated one and not the other.

But my point is there are reasons to use both. I have the new version of the valves and like how LinkTap warns me on water cutoff.  In fact it found low flow rate the other day which turned out to be an issue with our water line on a valve. 

If you wont do this I understand but i dont see how it could hurt to support it.   If you dont have anything scheduled with them it will ignore the command anyways.

**Comment by simplextech** [comment]
autoBack added to v0.1.11 as true.  I'll look into making this optional if someone else requests it for some reason.
